/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Services;
import EasyPass1.Welcome;
//import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
//import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//package Services;

/**
 *
 * @author Mezbah Uddin
 */
public class Bus extends javax.swing.JFrame {

    /**
     * Creates new form Bus
     */
    public Bus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        to = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        tgender = new javax.swing.JTextField();
        tfrom = new javax.swing.JTextField();
        tto = new javax.swing.JTextField();
        tdate = new javax.swing.JTextField();
        bback = new javax.swing.JButton();
        bsubmit = new javax.swing.JButton();
        bcancel = new javax.swing.JButton();
        JLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 80, 50);

        phone.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(255, 255, 255));
        phone.setText("Phone");
        jPanel1.add(phone);
        phone.setBounds(30, 90, 80, 29);

        gender.setBackground(new java.awt.Color(255, 255, 255));
        gender.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gender.setForeground(new java.awt.Color(255, 255, 255));
        gender.setText("Gender");
        jPanel1.add(gender);
        gender.setBounds(30, 150, 80, 29);

        from.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        from.setForeground(new java.awt.Color(255, 255, 255));
        from.setText("From");
        jPanel1.add(from);
        from.setBounds(400, 40, 70, 29);

        to.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        to.setForeground(new java.awt.Color(255, 255, 255));
        to.setText("To");
        jPanel1.add(to);
        to.setBounds(400, 90, 60, 29);

        date.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setText("Date");
        jPanel1.add(date);
        date.setBounds(400, 150, 80, 30);
        jPanel1.add(tname);
        tname.setBounds(130, 30, 200, 30);
        jPanel1.add(tphone);
        tphone.setBounds(130, 90, 200, 30);
        jPanel1.add(tgender);
        tgender.setBounds(130, 150, 200, 30);
        jPanel1.add(tfrom);
        tfrom.setBounds(500, 30, 210, 30);
        jPanel1.add(tto);
        tto.setBounds(500, 90, 210, 30);
        jPanel1.add(tdate);
        tdate.setBounds(500, 150, 210, 30);

        bback.setBackground(new java.awt.Color(6, 6, 68));
        bback.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bback.setForeground(new java.awt.Color(255, 255, 255));
        bback.setText("Back");
        bback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbackActionPerformed(evt);
            }
        });
        jPanel1.add(bback);
        bback.setBounds(90, 500, 100, 40);

        bsubmit.setBackground(new java.awt.Color(6, 6, 68));
        bsubmit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bsubmit.setForeground(new java.awt.Color(255, 255, 255));
        bsubmit.setText("Submit");
        bsubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubmitActionPerformed(evt);
            }
        });
        jPanel1.add(bsubmit);
        bsubmit.setBounds(310, 500, 100, 40);

        bcancel.setBackground(new java.awt.Color(6, 6, 68));
        bcancel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bcancel.setForeground(new java.awt.Color(255, 255, 255));
        bcancel.setText("Cancel");
        bcancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelActionPerformed(evt);
            }
        });
        jPanel1.add(bcancel);
        bcancel.setBounds(530, 500, 110, 40);

        JLable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Services/WhatsApp Image 2023-11-22 at 00.59.51_2e0ad2c3.jpg"))); // NOI18N
        jPanel1.add(JLable);
        JLable.setBounds(0, 0, 770, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelActionPerformed
          tname.setText("");
        tphone.setText(" ");
        tgender.setText("");
        JLable.setText("");
        tfrom.setText("");
        tto.setText("");
    }//GEN-LAST:event_bcancelActionPerformed

    private void bbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbackActionPerformed
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_bbackActionPerformed

    private void bsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubmitActionPerformed
        
        String name = tname.getText();
    String phone = tphone.getText();
    String gender = tgender.getText();
    String from = tfrom.getText();
    String to = tto.getText();
    String date = tdate.getText();

    String confirmMessage = "Name    : " + name + "\nPhone   : " + phone + "\nGender  : " + gender + "\nFrom      : " + from + "\nTo           : " + to + "\nDate       : " + date;

    int choice = JOptionPane.showConfirmDialog(rootPane, "Please confirm the following information:\n\n" + confirmMessage, "Confirm Data", JOptionPane.YES_NO_OPTION);

   // if (choice == JOptionPane.YES_OPTION) {
        // User confirmed, proceed with database insertion
      //  insertData(name, phone, gender, from, to, date);
    //}
//}
        
        
        
        
        String DateText = tdate.getText();
    
    // Use SimpleDateFormat to parse the String into a java.util.Date
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    java.util.Date utilDate;
    try {
        utilDate = sdf.parse(DateText);
        
        // Convert java.util.Date to java.sql.Date
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

        try {
            java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/ilog_in", "root", "root");

            String insertSQL = "INSERT INTO `bus` (`Name`, `Phone`, `Gender`, `From`, `To`, `Date`) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStatement = conn.prepareStatement(insertSQL);

            preparedStatement.setString(1, tname.getText());
            preparedStatement.setString(2, tphone.getText());
            preparedStatement.setString(3, tgender.getText());
            preparedStatement.setString(4, tfrom.getText());
            preparedStatement.setString(5, tto.getText());
            preparedStatement.setDate(6, sqlDate); // Set the SQL Date

            int rowsAffected = preparedStatement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data inserted successfully!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data insertion failed.");
            }

            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(Bus.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Database error: " + ex.getMessage());
        }
    } catch (java.text.ParseException e) {
        // Handle parsing exception, e.g., display an error message
        JOptionPane.showMessageDialog(rootPane, "Invalid date format. Please enter a date in yyyy-MM-dd format.");
    }
    }//GEN-LAST:event_bsubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLable;
    private javax.swing.JButton bback;
    private javax.swing.JButton bcancel;
    private javax.swing.JButton bsubmit;
    private javax.swing.JLabel date;
    private javax.swing.JLabel from;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField tdate;
    private javax.swing.JTextField tfrom;
    private javax.swing.JTextField tgender;
    private javax.swing.JTextField tname;
    private javax.swing.JLabel to;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField tto;
    // End of variables declaration//GEN-END:variables
}
